name: Notify RepoB on Changes

on:
  push:
    branches:
       - AWS-release
       
jobs:
  authenticate-user:
    runs-on: ubuntu-latest
    steps:
      - name: Request OAuth Authentication
        run: |
          echo "Visit this URL to authenticate:"
          echo "https://github.com/login/oauth/authorize?client_id=${{ secrets.CLIENT_ID }}&scope=repo"

          # Pause execution for authentication
          sleep 30
          
          echo "User authentication required"

      - name: Generate GitHub App Token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Send Repository Dispatch Event
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
               https://api.github.com/repos/${{ secrets.REPO_B }}/dispatches \
               -d '{"event_type": "new-update"}'
               
               